
front_page_overview = """ This website allows you to explore machine learning models that perform similarly well - their differences and similarities.
Analyze how models differ in their predictions, how consistent they are, and what trade-offs exist on the chosen dataset. 
Discover alternative solutions to ensure the right, fair and unbiased desicion making. 
"""

package_overview = """
This application is built on the Python library ARSA_ML, which allows users to analyze sets of models trained for a particular classification problem.
It was developed to enable experimentation with the library's features in a no-code environment through an interactive interface and pre-saved datasets. 
All available datasets and their characteristics are described on the <strong> Datasets page</strong>. The application consists of two analytical dashboards : the <strong> Rashomon page </strong> and the <strong>Intersection page</strong>. 
Detailed explanations of the key concepts, such as the Rashomon Set, the Rashomon Intersection, and all related metrics, are provided in the sections below to help users better understand the analysis.  

"""

rashomon_set_definition ="""
To understand the concept of the Rashomon Set, let's consider the situation illustrated by the diagram on the left. In many real-world cases, decision-makers train multiple models, evaluate their performance, and base their decisions on the predictions of the best-performing model.
However, as the diagram shows, there are often many models with similarly strong performance. For example, Model 1 might achieve 0.99 accuracy, while Model 2 is only 1% lower.
<strong>The Rashomon Set</strong> consists of all models whose performance is within a small margin (epsilon) of the best model. 
Among them, the model with the highest score is called the <strong>base model</strong>, and the others are referred to as <strong>competing models</strong>.

"""

rashomon_set_situation="""
Regarding the illustration, the best model predicted the negative class for the client number 10. Depending on the classification problem, this could mean that the client will not receive a loan or insurance, or that they are not a carrier of a disease.
Upon closer examination of this situation, we notice that Model 2 is a part of the Rashomon Set if we allow an error margin of 1%. This second model, while achieving similarly strong overall performance, gives a different prediction for the client number 10. This problem is reffered to as <strong>predictive multiplicity problem</strong>.
<br><br>It raises an important question : what would change if we chose the competing model over the best model? Perhaps, Model 2 is more interpretable, more stable and might even be preferable to Model 1. <br> <br>
All of these considerations should be carefully analyzed before making any final decisions, especially when these decisions have a direct impact on people's lives, to ensure that each decision can be clearly explained and that individuals can trust that their prediction is final and well-founded. 

"""
rashomon_metrics="""
 • <strong>Rashomon Ratio</strong> - the proportion of models that are included in the Rashomon Set from all trained models. <br>
 • <strong>Rashomon Pattern Ratio</strong> - the fraction of unique prediction patterns generated by the models in the Rashomon Set, relative to the number of patterns generated by all available models.  <br>
 • <strong>Ambiguity</strong> - the proportion of individual predictions that could change over the set of competing models.<br>
 • <strong>Probabilistic Ambiguity</strong> - has the same interpretation as Ambiguity but takes and additional paremeter (delta), which is used to distinguish meaningful differences in risk probabilities.<br>
 • <strong>Discrepancy</strong> - the maximum proportion of predictions that would change if another competing model was chosen.<br>
 • <strong>Probabilistic Discrepancy</strong> - has the same interpretation as Discrepancy but takes and additional paremeter (delta), which is used to distinguish meaningful differences in risk probabilities.<br>
 • <strong>VPR (Viable Prediction Range)</strong> - for each observation, it is calculated as [min probability; max probability] predicted by all models from the Rashomon Set. Wide VPR suggests high uncertainty.<br>
 • <strong>Agreement Rate</strong> - for each observation, it is calculated as the proportion of models, which made the same class prediction as the base model. Agreement rate = 1 suggests that all models agreed with the base model.<br>
 • <strong>Percent Agreement</strong> - for each model in the Rashomon Set, it is calculated as the proportion of observations for which the model and the base model made the same predictions.<br>
 • <strong>Cohen's Kappa</strong> - for each model in the Rashomon Set, measures agreement between the model's and the base model's predictions adjusted for agreement expected to occur by chance.<br>
 • <strong>Rashomon Capacity</strong> - for a given sample, Rashomon Capacity measures the diveristy of probability predictions made by the models in the Rashomon Set.<br>

"""


rashomon_intersection_definition ="""
To further analyze the concept of the Rashomon Set, we introduce an additional apporach - the Rashomon Intersection.
It is based on the idea that one may want to maximize not just one, but two evaluation metrics.
Let's consider the situation illustrated by the diagram on the left. 
While we can analyze two separate Rashomon Sets (for accuracy and recall), we may also be interested in which of our models achieved similarly high scores in both metrics. 
According to the chart, Models 3 and 4 present good scores in both metrics, so they are included in the Rashomon Intersection. 
On the other hand, Models 1, 2, and 5 are included in the Intersection, as they did not perform similarly well regarding both metrics.
"""

bibliography ="""
1. <a href="https://dl.acm.org/doi/10.5555/3524938.3525566" target="_blank">Definition of predictive multiplicity and the Rashomon Set for classification problems</a> <br>
2. <a href="https://dl.acm.org/doi/10.1609/aaai.v37i9.26227" target="_blank">Definitions of the Rashomon Set metrics in probabilistic classification</a> <br>
3. <a href="https://dl.acm.org/doi/10.5555/3600270.3602371" target="_blank">Rashomon Capacity</a><br>
4. <a href="https://link.springer.com/chapter/10.1007/978-981-99-1521-7_7" target="_blank">Weighted Sum in multi-objective optimization</a><br>
5. <a href="https://link.springer.com/chapter/10.1007/3-540-27659-9_1" target="_blank">Multi-objective optimization</a><br>
6. <a href="https://dl.acm.org/doi/10.1145/3610536" target="_blank">Pareto Front</a><br>
7. <a href="https://autogluon.ai" target="_blank">AutoGluon library</a><br>
8. <a href="https://h2o.ai/" target="_blank">H2O AutoML library</a><br>
This product uses AutoGluon, H2O and Streamlit open source libraries under Apache License 2.0.
"""

